#syntax=docker/dockerfile:1.5

FROM node:16.1-alpine 

ENV NODE_ENV=production

WORKDIR /usr/app/src

COPY package*.json ./

RUN --mount=type=cache,target=/usr/app/src/.npm \
    npm set cache /usr/app/src/.npm && \
    npm ci --only=production

USER node

COPY --chown=node:node ./src/ .

CMD [ "npm","run","dev" ]